In [54]:
# prompt: read csv files

import pandas as pd

df = pd.read_csv('merged_file - merged_file.csv.csv')

In [55]:
df

,Title Incident Report,Segment,Location,Date,Department / Area,Incident Type,Process,Operation Mode,Machine Category,Machine Type,Riskfactor,Repeat Incident,Maximum Possible Damage/Harm Occurred,Employee_Type,Gender,Type of Injury,Injured Body Part,Lost Days,Damage/Harm Sufficient and Correct in RA?
0,crush finger of the right hand,SY,ElJem,21/1/2019,MR,A3,I - 4008 - assembly,Normal mode,Other,NaN,10.2 Work organization,YES,YES,DRX,Male,Bruise,Hand,7.0,NO
1,Contusion of the left hand,SY,ElJem,16/1/2019,Production,A3,I - 4008 - assembly,Normal mode,Other,NaN,8.4 Inadequate escape routes,NO,YES,DRX,Female,Bruise,Hand,10.0,NO
2,Low back pain,SY,ElJem,29/1/2019,IR,A3,I - 4023 - foldback,Normal mode,Other,-,10.2 Work organization,YES,YES,DRX,Male,Sprain / Strain,Body,15.0,NO
3,trauma of the right hand,SY,ElJem,20/2/2019,MR,A3,I - 4008 - assembly,Normal mode,Other,NaN,8.5 Insufficient room to move at the workplace...,YES,YES,DRX,Female,Bruise,Hand,15.0,YES
4,eye trauma,SY,ElJem,25/2/2019,MM,A3,I - 4008 - assembly,Normal mode,Other,NaN,8.4 Inadequate escape routes,YES,YES,DRX,Female,Other,Eye,13.0,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
518,back sprain trouma,Electric,Jemmal,14 November 2024,Production,A2-Injury with lost time,E-Assembly - Item number,NaN,Work place / paths,NaN,11.2 - Humans,NO,NO,DRX,Female,Sprain / strain,Body,5.0,NO
519,trauma to the right hand with edema,Electric,Jemmal,16 November 2024,Production,A2-Injury with lost time,Other,NaN,Work place / paths,Plastic box,3.8 - Impeded handling of work equipment,NO,NO,DRX,Male,Fracture,Hand,31.0,NO
520,Back sprain due to tripping,Electric,Jemmal,02 December 2024,IR,A2-Injury with lost time,E-Final Assembly - Customer order,NaN,Work place / paths,anti fatigue mat,2.1 - Working spaces,NO,YES,DRX,Female,Sprain / Strain,Body,27.0,YES
521,Wound due to connecter,Electric,Jemmal,06 December 2024,Production,A2-Injury with lost time,E-Assembly - Item number,NaN,Tools / Utilities,cable connector,3.8 - Impeded handling of work equipment,NO,YES,DRX,Male,Laceration,Hand,5.0,YES
522,Foot injury,Interior,Rosslyn,24 June 2024,Logistics,A2-Injury with lost time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DRX,NaN,NaN,Foot,20.0,NaN

In [56]:
#date reformulation make it all at the same format
df['Date'] = pd.to_datetime(df['Date'], format= 'mixed')

In [57]:
df

,Title Incident Report,Segment,Location,Date,Department / Area,Incident Type,Process,Operation Mode,Machine Category,Machine Type,Riskfactor,Repeat Incident,Maximum Possible Damage/Harm Occurred,Employee_Type,Gender,Type of Injury,Injured Body Part,Lost Days,Damage/Harm Sufficient and Correct in RA?
0,crush finger of the right hand,SY,ElJem,2019-01-21,MR,A3,I - 4008 - assembly,Normal mode,Other,NaN,10.2 Work organization,YES,YES,DRX,Male,Bruise,Hand,7.0,NO
1,Contusion of the left hand,SY,ElJem,2019-01-16,Production,A3,I - 4008 - assembly,Normal mode,Other,NaN,8.4 Inadequate escape routes,NO,YES,DRX,Female,Bruise,Hand,10.0,NO
2,Low back pain,SY,ElJem,2019-01-29,IR,A3,I - 4023 - foldback,Normal mode,Other,-,10.2 Work organization,YES,YES,DRX,Male,Sprain / Strain,Body,15.0,NO
3,trauma of the right hand,SY,ElJem,2019-02-20,MR,A3,I - 4008 - assembly,Normal mode,Other,NaN,8.5 Insufficient room to move at the workplace...,YES,YES,DRX,Female,Bruise,Hand,15.0,YES
4,eye trauma,SY,ElJem,2019-02-25,MM,A3,I - 4008 - assembly,Normal mode,Other,NaN,8.4 Inadequate escape routes,YES,YES,DRX,Female,Other,Eye,13.0,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
518,back sprain trouma,Electric,Jemmal,2024-11-14,Production,A2-Injury with lost time,E-Assembly - Item number,NaN,Work place / paths,NaN,11.2 - Humans,NO,NO,DRX,Female,Sprain / strain,Body,5.0,NO
519,trauma to the right hand with edema,Electric,Jemmal,2024-11-16,Production,A2-Injury with lost time,Other,NaN,Work place / paths,Plastic box,3.8 - Impeded handling of work equipment,NO,NO,DRX,Male,Fracture,Hand,31.0,NO
520,Back sprain due to tripping,Electric,Jemmal,2024-12-02,IR,A2-Injury with lost time,E-Final Assembly - Customer order,NaN,Work place / paths,anti fatigue mat,2.1 - Working spaces,NO,YES,DRX,Female,Sprain / Strain,Body,27.0,YES
521,Wound due to connecter,Electric,Jemmal,2024-12-06,Production,A2-Injury with lost time,E-Assembly - Item number,NaN,Tools / Utilities,cable connector,3.8 - Impeded handling of work equipment,NO,YES,DRX,Male,Laceration,Hand,5.0,YES
522,Foot injury,Interior,Rosslyn,2024-06-24,Logistics,A2-Injury with lost time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DRX,NaN,NaN,Foot,20.0,NaN

In [45]:
#eliminate NAN values from operation mode column
df_clean = df.dropna(subset=['Operation Mode'])

In [46]:
df_clean

,Title Incident Report,Segment,Location,Date,Department / Area,Incident Type,Process,Operation Mode,Machine Category,Machine Type,Riskfactor,Repeat Incident,Maximum Possible Damage/Harm Occurred,Employee_Type,Gender,Type of Injury,Injured Body Part,Lost Days,Damage/Harm Sufficient and Correct in RA?
0,crush finger of the right hand,SY,ElJem,2019-01-21,MR,A3,I - 4008 - assembly,Normal mode,Other,NaN,10.2 Work organization,YES,YES,DRX,Male,Bruise,Hand,7.0,NO
1,Contusion of the left hand,SY,ElJem,2019-01-16,Production,A3,I - 4008 - assembly,Normal mode,Other,NaN,8.4 Inadequate escape routes,NO,YES,DRX,Female,Bruise,Hand,10.0,NO
2,Low back pain,SY,ElJem,2019-01-29,IR,A3,I - 4023 - foldback,Normal mode,Other,-,10.2 Work organization,YES,YES,DRX,Male,Sprain / Strain,Body,15.0,NO
3,trauma of the right hand,SY,ElJem,2019-02-20,MR,A3,I - 4008 - assembly,Normal mode,Other,NaN,8.5 Insufficient room to move at the workplace...,YES,YES,DRX,Female,Bruise,Hand,15.0,YES
4,eye trauma,SY,ElJem,2019-02-25,MM,A3,I - 4008 - assembly,Normal mode,Other,NaN,8.4 Inadequate escape routes,YES,YES,DRX,Female,Other,Eye,13.0,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
344,Right knee sprain,Electric,SousseMETS,2021-11-19,Logistics,A3-downtime > 3 days,Other,Normal operation,NaN,NaN,-,NO,NaN,DRX,Female,Bruise,Leg,6.0,YES
345,Thumb and left knee injury,Electric,SousseMETS,2021-11-19,BX8,A3-downtime > 3 days,Other,Normal operation,Conveyor System / Robot,NaN,1.2 Parts with dangerous surfaces,NO,NO,DRX,Female,Stab injury,Hand,6.0,YES
346,Elbow Dislocation and Ligament Injury,Electric,SousseMETS,2021-11-25,BX8,A3-downtime > 3 days,Other,Normal operation,NaN,NaN,8.5 Insufficient room to move at the workplace...,NO,NaN,DRX,Female,Sprain / Strain,Arm,21.0,YES
347,Elbow Injury,Electric,SousseMETS,2021-11-26,BX8,A3-downtime > 3 days,Other,Normal operation,NaN,NaN,8.5 Insufficient room to move at the workplace...,NO,NaN,DRX,Female,Sprain / Strain,Arm,5.0,YES
348,Finger Injury,Electric,SousseMETS,2021-12-01,Logistics,A3-downtime > 3 days,Logistics,Normal operation,NaN,NaN,"9.1 Lifting, holding, carrying or pulling, pus...",NO,NaN,DRX,Female,Other,Hand,12.0,YES

In [58]:
df['Machine Type'] = df['Machine Type'].replace('No involved machine', 'no machine')

In [59]:
df['Machine Type'] = df['Machine Type'].replace('No involved Machine', 'no machine')

In [60]:
for item in df['Machine Type']:
    print(item)

nan
nan
-
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
AGV SYSTEM
nan
nan
-
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
tesa cutter
nan
nan
nan
nan
Ushall
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
AGV SYSTEM
nan
Reach Truck
nan
nan
no machine
no machine
no machine
no machine
nan
no machine
no machine
no machine
no machine
no machine
no machine
no machine
no machine
no machine
no machine
no machine
no machine
no machine
no machine
no machine
no machine
no machine
no machine
no machine
no machine
no machine
no machine
no machine
no machine
nan
no machine
no machine
no machine
no machine
no machine
no machine
no machine
no machine
no machine
no machine
no machine
no machine
no machine
no machine
no machine
no machine
no machine
no machine
no machine
no machine
no machine
nan
Machine CRMP CENTER 365
nan
nan
nan
nan
nan
Press MFU
forklift
nan
nan
SERTISSAGE (::)
nan
nan
nan
nan
nan
nan
nan
Hanke
nan
SCHÄFER
Coupe tesa
nan
Hanke 971
nan
nan
nan
nan
plan de travail
nan
nan
nan
HANKE
nan
nan
nan
nan
nan
chariot
schaeffer
nan
nan
nan
nan
nan
nan
nan
nan
Hanke 971
nan
nan
nan
trolley
nan
nan
nan
nan
nan
nan
Komax alpha 355
nan
nan
nan
schleuniger
Plan de travail
nan
nan
nan
nan
nan
Staple gun
Porte
Steps
nan
cutting mold
Mold of foam injection
product transport trolley
Baubrettbeförderer
Baubrett
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
KOMAX
nan
nan
nan
nan
nan
nan
couvercle de rProductionrk en bois
-
Foam injection robot
nan
nan
machine coupe schlauch N10741/002
nan
Cutting machine
nan
nan
nan
Schleuniger
nan
pistolet
nan
nan
nan
nan
pistolet
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
machine coupe schlauch N10741/002
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
slippery ground
slippery ground
slippery ground
metal support
marble
rearing trolley
nan
cart
nan
nan
nan
KSK Branch
Metal support of the water bottles
Palette
Commission kit
nan
Gable
-
nan
nan
nan
nan
nan
Pistolet pneumatique
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
chariot elevateur
nan
nan
nan
nan
nan
nan
nan
nan
nan
-
-
_
nan
nan
nan
nan
nan
nan
-
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
Ladders
nan
nan
nan
nan
nan
nan
Machine 061 schluniger
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
Schleuniger CrimpCenter 63
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
Pistole
nan
nan
nan
nan
nan
nan
Trolley
Trolley
nan
Conveyor system
nan
circular saw
Lagger
nan
nan
nan
nan
nan
nan
Amaisa
nan
Transpalet
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
Sewing
AP2_JLR
Assembly
nan
nan
nan
crimping machine
nan
nan
nan
Baubrett (Assembly line)
nan
nan
nan
nan
nan
nan
Electric screwdriver
stepladder
workstation
support metalique
plastic boxes
foaming ingection machine
Metal support
nan
nan
stepladder locking bracket
shelfs
Electrical function test
Nutrunner
racks
support metallique
trolley
trolley
the Guillot support
the pince of boutel
stepladder
Tesa spender
Three-hole expansion pliers (HWZ)
nan
nan
nan
nan
nan
nan
Schafer-736
nan
nan
nan
nan
Blade Holder
nan
nan
nan
HANKE 11290/044
nan
nan
Fire fighting door
wooden pallet in the production process
nan
nan
nan
nan
nan
nan
KOMAX 253
metal cart
IR table structure
changing room floor
plastic box
changing room
foaming machine mold
feeding workstation
nan
Plastic box
anti fatigue mat
cable connector
nan

In [61]:
# prompt: SAVA the csv file

df.to_csv('cleaned_merged_file_final.csv', index=False)